### ISSUE TITLE
пропертис нельзя задать через параметр TagConfigFile в версии 1.6.0

### ISSUE THREAD

**Issue by SvetlanaUtina** [sbtqa/qa-utils#29]
https://github.com/sbtqa/qa-utils/blob/master/src/main/java/ru/sbtqa/tag/qautils/properties/Props.java

метод settings.
если задать другое пропертис через параметр TagConfigFile, то получится значение параметра TagConfigFile/application.properties

**Comment by kosteman** [comment]
Все верно, там перепутаны немного названия.
Задача в том, чтобы использовать файл пропертис с именем отличным от application.properties?

**Comment by SvetlanaUtina** [comment]
@kosteman ранее можно было задавать путь с наименованием файла в ресурсах. Сделала также в пр https://github.com/sbtqa/qa-utils/pull/30

**Comment by kosteman** [comment]
Как именно задавался этот параметр?

Сейчас сделал следующим образом:
mvn clean test -DTagConfigFile=qwerty 
файл с параметрами положил вот так
qwerty/application.properties
Всё работает, параметры берутся именно оттуда.

Пока единственной проблемой вижу неправильный нейминг, должно быть -DTagConfigFileFolder=qwerty

**Comment by SvetlanaUtina** [comment]
@kosteman у вас в доке показано, что можно переопределить путь и само наименование файла с  помощью этой переменной. Вот я так и сделала.
то есть -DTagConfigFile=custom/customConfig.properties

версия 1.5.0
класс ru.sbtqa.tag.qautils.properties.Props
`
private static void initProperties() {
        String sConfigFile = System.getProperty("TagConfigFile", "config/application.properties");
        properties = new Properties();
        LOG.debug("Loading properties from {}", sConfigFile);

        try {
            InputStream streamFromResources = Props.class.getClassLoader().getResourceAsStream(sConfigFile);
            Throwable var2 = null;

            try {
                InputStreamReader isr = new InputStreamReader(streamFromResources, "UTF-8");
                properties.load(isr);
            } catch (Throwable var12) {
                var2 = var12;
                throw var12;
            } finally {
                if (streamFromResources != null) {
                    if (var2 != null) {
                        try {
                            streamFromResources.close();
                        } catch (Throwable var11) {
                            var2.addSuppressed(var11);
                        }
                    } else {
                        streamFromResources.close();
                    }
                }

            }

        } catch (NullPointerException | IOException var14) {
            throw new PropsRuntimeException("Failed to access properties file", var14);
        }
    }`

**Comment by SvetlanaUtina** [comment]
я считаю это неудобным когда у тебя допустим 6 конфигов, все они называются application.properties и для них необходимо 6 папок в ресурсах создавать.

**Comment by kosteman** [comment]
Согласен. Откомментировал pr

**Comment by kosteman** [comment]
closed #30
