### ISSUE TITLE
Чтение properties из файла при каждом обращении

### ISSUE THREAD

**Issue by webrelab** [sbtqa/qa-utils#31]
https://github.com/sbtqa/qa-utils/blob/0624ee4c0ed6341ddac697d1362caefb402d716d/src/main/java/ru/sbtqa/tag/qautils/properties/Props.java#L81

Когда я получаю проперти Props.get("property.name") - каждый раз выполняется initProperties() и соответственно чтение одних и тех же пропертей из файла. Это нормально? Ещё до старта браузера чтение из файла выполняется около 10 раз, и потом ещё по ходу исполнения тоже немало обращений.
Мне, например, это не позволяет в Props записать свою проперти в runtime, так как при её запросе она будет перезаписана данными из файла

**Comment by clicman** [comment]
Хммм. На сколько я помню была фича переопределении свойств в рантайме. Вы отдельно или в контексте pf2 используете?
Так же посмотрю, что там с чтением. Но завтра уже.

**Comment by clicman** [comment]
Так, а почему вы этот метод дергаете? Там есть как-минимум getInstance(), которые так не делает и еще прямые get на значения по ключу, которые тоже ничего не переинициализируют

**Comment by webrelab** [comment]
Props.get(name) дёргает приватный getProp(name), тот в свою очередь дёргает getProps(), который сначала выполняет initProperties() а потом возвращает поле properties.
Использую в контексте pf2

**Comment by clicman** [comment]
@webrelab спасибо за тикет! Завтра выпустим новые версии всех проектов, зависящих от qa-utils.

**Comment by clicman** [comment]
Так же исправлено в https://github.com/sbtqa/page-factory-2/releases/tag/15.4.5
